Repository seoulmate7/Seoulmate_Backend, pull requests merged in 2025-07, with the labels that each got.

#5 [Feat/#1] 멤버, 취미 엔티티 생성 및 이니셜라이저 추가
  .github/pull_request_template.md
  src/main/java/com/nexus/seoulmate/domain/member/domain/Hobby.java
  src/main/java/com/nexus/seoulmate/domain/member/domain/Member.java
  src/main/java/com/nexus/seoulmate/domain/member/domain/enums/AuthProvider.java
  src/main/java/com/nexus/seoulmate/domain/member/domain/enums/Countries.java
  src/main/java/com/nexus/seoulmate/domain/member/domain/enums/HobbyCategory.java
  src/main/java/com/nexus/seoulmate/domain/member/domain/enums/Languages.java
  src/main/java/com/nexus/seoulmate/domain/member/domain/enums/Role.java
  src/main/java/com/nexus/seoulmate/domain/member/domain/enums/University.java
  src/main/java/com/nexus/seoulmate/domain/member/domain/enums/UserStatus.java
  src/main/java/com/nexus/seoulmate/domain/member/domain/enums/VerificationStatus.java
  src/main/java/com/nexus/seoulmate/domain/member/repository/HobbyRepository.java
  src/main/java/com/nexus/seoulmate/domain/member/repository/MemberRepository.java
  src/main/java/com/nexus/seoulmate/domain/test/TestMember.java
  src/main/java/com/nexus/seoulmate/domain/test/TestMemberController.java
  src/main/java/com/nexus/seoulmate/domain/test/TestMemberRepository.java
  src/main/java/com/nexus/seoulmate/mock/HobbyDataInitializer.java
  src/main/java/com/nexus/seoulmate/mock/MemberTestDataInitializer.java
Labels: ✨ feature

#7 [Feat/#3] official, private 모임 crud 구현
  .gitignore
  build.gradle
  src/main/java/com/nexus/seoulmate/config/SwaggerConfig.java
  src/main/java/com/nexus/seoulmate/domain/member/domain/enums/Languages.java
  src/main/java/com/nexus/seoulmate/exception/status/ErrorStatus.java
  src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
  src/main/java/com/nexus/seoulmate/meeting/api/MeetingOfficialController.java
  src/main/java/com/nexus/seoulmate/meeting/api/MeetingPrivateController.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/officiaReq/MeetingCreateOfficialReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/officiaReq/MeetingUpdateOfficialReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/privateReq/MeetingCreatePrivateReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/privateReq/MeetingUpdatePrivateReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/MeetingDetailOfficialRes.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/MeetingDetailPrivateRes.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/MeetingListRes.java
  src/main/java/com/nexus/seoulmate/meeting/application/officialMeeting/OfficialMeetingService.java
  src/main/java/com/nexus/seoulmate/meeting/application/officialMeeting/OfficialMeetingServiceImpl.java
  src/main/java/com/nexus/seoulmate/meeting/application/privateMeeting/PrivateMeetingService.java
  src/main/java/com/nexus/seoulmate/meeting/application/privateMeeting/PrivateMeetingServiceImpl.java
  src/main/java/com/nexus/seoulmate/meeting/domain/Meeting.java
  src/main/java/com/nexus/seoulmate/meeting/domain/MeetingType.java
  src/main/java/com/nexus/seoulmate/meeting/domain/repository/MeetingRepository.java
Labels: ✨ feature

#9 [feat/#2] [CICD] CI/CD 파이프라인 구축 , AWS S3 Presigned-URL 구현
  .github/workflows/dev_depoly.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/nexus/seoulmate/aws/config/AmazonConfig.java
  src/main/java/com/nexus/seoulmate/aws/controller/AmazonS3Controller.java
  src/main/java/com/nexus/seoulmate/aws/entity/Uuid.java
  src/main/java/com/nexus/seoulmate/aws/entity/UuidRepository.java
  src/main/java/com/nexus/seoulmate/aws/s3/AmazonS3Manager.java
  src/main/java/com/nexus/seoulmate/aws/service/AmazonS3Service.java
  src/main/java/com/nexus/seoulmate/config/S3Config.java
Labels: 🖧 cicd

#13 2025.07.30 develop 브랜치를 main 브랜치로 병합
  .github/workflows/dev_depoly.yml
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/nexus/seoulmate/aws/config/AmazonConfig.java
  src/main/java/com/nexus/seoulmate/aws/controller/AmazonS3Controller.java
  src/main/java/com/nexus/seoulmate/aws/entity/Uuid.java
  src/main/java/com/nexus/seoulmate/aws/entity/UuidRepository.java
  src/main/java/com/nexus/seoulmate/aws/s3/AmazonS3Manager.java
  src/main/java/com/nexus/seoulmate/aws/service/AmazonS3Service.java
  src/main/java/com/nexus/seoulmate/config/FluentApiProperties.java
  src/main/java/com/nexus/seoulmate/config/RestTemplateConfig.java
  src/main/java/com/nexus/seoulmate/config/SwaggerConfig.java
  src/main/java/com/nexus/seoulmate/exception/CustomException.java
  src/main/java/com/nexus/seoulmate/exception/GlobalExceptionalHandler.java
  src/main/java/com/nexus/seoulmate/exception/Response.java
  src/main/java/com/nexus/seoulmate/exception/status/ErrorStatus.java
  src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
  src/main/java/com/nexus/seoulmate/meeting/api/MeetingOfficialController.java
  src/main/java/com/nexus/seoulmate/meeting/api/MeetingPrivateController.java
  src/main/java/com/nexus/seoulmate/meeting/api/MeetingSearchController.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/MeetingSearchReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/officiaReq/MeetingCreateOfficialReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/officiaReq/MeetingUpdateOfficialReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/privateReq/MeetingCreatePrivateReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/privateReq/MeetingUpdatePrivateReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/MeetingDetailOfficialRes.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/MeetingDetailPrivateRes.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/MeetingListRes.java
  src/main/java/com/nexus/seoulmate/meeting/application/officialMeeting/OfficialMeetingService.java
  src/main/java/com/nexus/seoulmate/meeting/application/officialMeeting/OfficialMeetingServiceImpl.java
  src/main/java/com/nexus/seoulmate/meeting/application/privateMeeting/PrivateMeetingService.java
  src/main/java/com/nexus/seoulmate/meeting/application/privateMeeting/PrivateMeetingServiceImpl.java
  src/main/java/com/nexus/seoulmate/meeting/application/search/MeetingSearchService.java
  src/main/java/com/nexus/seoulmate/meeting/application/search/MeetingSearchServiceImpl.java
  src/main/java/com/nexus/seoulmate/meeting/domain/Meeting.java
  src/main/java/com/nexus/seoulmate/meeting/domain/MeetingType.java
  src/main/java/com/nexus/seoulmate/meeting/domain/repository/MeetingCustomRepository.java
  src/main/java/com/nexus/seoulmate/meeting/domain/repository/MeetingCustomRepositoryImpl.java
  src/main/java/com/nexus/seoulmate/meeting/domain/repository/MeetingRepository.java
  src/main/java/com/nexus/seoulmate/member/controller/FluentProxyController.java
  src/main/java/com/nexus/seoulmate/member/controller/MemberController.java
  src/main/java/com/nexus/seoulmate/member/domain/Hobby.java
  src/main/java/com/nexus/seoulmate/member/domain/Member.java
  src/main/java/com/nexus/seoulmate/member/domain/enums/AuthProvider.java
  src/main/java/com/nexus/seoulmate/member/domain/enums/Countries.java
  src/main/java/com/nexus/seoulmate/member/domain/enums/HobbyCategory.java
  src/main/java/com/nexus/seoulmate/member/domain/enums/Languages.java
  src/main/java/com/nexus/seoulmate/member/domain/enums/Role.java
  src/main/java/com/nexus/seoulmate/member/domain/enums/University.java
  src/main/java/com/nexus/seoulmate/member/domain/enums/UserStatus.java
  src/main/java/com/nexus/seoulmate/member/domain/enums/VerificationStatus.java
  src/main/java/com/nexus/seoulmate/member/repository/HobbyRepository.java
  src/main/java/com/nexus/seoulmate/member/repository/MemberRepository.java
  src/main/java/com/nexus/seoulmate/member/service/FluentProxyService.java
  src/main/java/com/nexus/seoulmate/mock/HobbyDataInitializer.java
  src/main/java/com/nexus/seoulmate/mock/MemberTestDataInitializer.java
  src/main/resources/application.yml
Labels: 🔧 chore

#16 application-prod 깃허브 시크릿 추가
  .github/workflows/dev_depoly.yml
Labels: 🔧 chore

#17 Docker 내부 MYSQL CI환경에 추가
  .github/workflows/dev_depoly.yml
Labels: 🐞 bug

#19 deploy 쪽 artifact 수정
  .github/workflows/dev_depoly.yml
Labels: 🐞 bug

#20 스웨거 배포 환경에 맞게 수정
  .github/workflows/dev_depoly.yml
Labels: 🔨 mod

#21 스웨거 배포 환경에 맞게 수정(bootJar)
  .github/workflows/dev_depoly.yml
Labels: 🔨 mod

#22 스웨거 배포 환경에 맞게 수정(bootJar) + 이전 캐시 삭제
  .github/workflows/dev_depoly.yml
Labels: 🔨 mod
