Repository seoulmate7/Seoulmate_Backend, pull requests merged in 2025-08, with the labels that each got.

#27 [MOD/#4] 언어 평가 스크립트 할당
  src/main/java/com/nexus/seoulmate/member/service/FluentProxyService.java
Labels: 🔨 mod

#35 [FEAT/#11] 결제 기능 구현
  .DS_Store
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/nexus/seoulmate/config/IamportConfig.java
  src/main/java/com/nexus/seoulmate/exception/status/ErrorStatus.java
  src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
  src/main/java/com/nexus/seoulmate/meeting/api/MeetingParticipantController.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/officiaReq/MeetingCreateOfficialReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/privateReq/MeetingCreatePrivateReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/ParticipantDto.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/ParticipantsResDto.java
  src/main/java/com/nexus/seoulmate/meeting/application/participant/MeetingParticipantService.java
  src/main/java/com/nexus/seoulmate/meeting/application/participant/MeetingParticipantServiceImpl.java
  src/main/java/com/nexus/seoulmate/order/api/OrderController.java
  src/main/java/com/nexus/seoulmate/order/api/dto/response/CreateOrderResDto.java
  src/main/java/com/nexus/seoulmate/order/application/OrderService.java
  src/main/java/com/nexus/seoulmate/order/domain/Order.java
  src/main/java/com/nexus/seoulmate/order/domain/OrderStatus.java
  src/main/java/com/nexus/seoulmate/order/domain/repository/OrderRepository.java
  src/main/java/com/nexus/seoulmate/payment/api/PaymentController.java
  src/main/java/com/nexus/seoulmate/payment/api/PaymentResultController.java
  src/main/java/com/nexus/seoulmate/payment/api/dto/WebhookPayload.java
  src/main/java/com/nexus/seoulmate/payment/api/dto/request/PaymentApprovalReqDto.java
  src/main/java/com/nexus/seoulmate/payment/api/dto/request/PaymentVerifyRequest.java
  src/main/java/com/nexus/seoulmate/payment/api/dto/response/PaymentApprovalResDto.java
  src/main/java/com/nexus/seoulmate/payment/application/PaymentService.java
  src/main/java/com/nexus/seoulmate/payment/domain/Payment.java
  src/main/java/com/nexus/seoulmate/payment/domain/PaymentStatus.java
  src/main/resources/.DS_Store
  src/main/resources/application.yml
  src/main/resources/static/test-payment.html
Labels: ✨ feature

#37 [MERGE] 2025.08.09
  .DS_Store
  .github/workflows/dev_depoly.yml
  build.gradle
  run.sh
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/nexus/seoulmate/config/IamportConfig.java
  src/main/java/com/nexus/seoulmate/exception/status/ErrorStatus.java
  src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
  src/main/java/com/nexus/seoulmate/meeting/api/MeetingParticipantController.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/officiaReq/MeetingCreateOfficialReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/privateReq/MeetingCreatePrivateReq.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/ParticipantDto.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/ParticipantsResDto.java
  src/main/java/com/nexus/seoulmate/meeting/application/participant/MeetingParticipantService.java
  src/main/java/com/nexus/seoulmate/meeting/application/participant/MeetingParticipantServiceImpl.java
  src/main/java/com/nexus/seoulmate/order/api/OrderController.java
  src/main/java/com/nexus/seoulmate/order/api/dto/response/CreateOrderResDto.java
  src/main/java/com/nexus/seoulmate/order/application/OrderService.java
  src/main/java/com/nexus/seoulmate/order/domain/Order.java
  src/main/java/com/nexus/seoulmate/order/domain/OrderStatus.java
  src/main/java/com/nexus/seoulmate/order/domain/repository/OrderRepository.java
  src/main/java/com/nexus/seoulmate/payment/api/PaymentController.java
  src/main/java/com/nexus/seoulmate/payment/api/PaymentResultController.java
  src/main/java/com/nexus/seoulmate/payment/api/dto/WebhookPayload.java
  src/main/java/com/nexus/seoulmate/payment/api/dto/request/PaymentApprovalReqDto.java
  src/main/java/com/nexus/seoulmate/payment/api/dto/request/PaymentVerifyRequest.java
  src/main/java/com/nexus/seoulmate/payment/api/dto/response/PaymentApprovalResDto.java
  src/main/java/com/nexus/seoulmate/payment/application/PaymentService.java
  src/main/java/com/nexus/seoulmate/payment/domain/Payment.java
  src/main/java/com/nexus/seoulmate/payment/domain/PaymentStatus.java
  src/main/resources/.DS_Store
  src/main/resources/application.yml
  src/main/resources/static/test-payment.html
Labels: 🖧 cicd

#38 [MERGE] 2025.08.09 자동 배포 안되는 문제 수정
  .github/workflows/dev_depoly.yml
  Dockerfile
  src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
Labels: 🖧 cicd

#40 [MERGE] 배포 앱 죽는 에러 해결
  docker-compose.yml
  src/main/resources/application.yml
Labels: 🐞 bug

#41 [MERGE] 배포 앱 죽는 에러 해결2
  src/main/java/com/nexus/seoulmate/mock/HobbyDataInitializer.java
Labels: 🐞 bug

#42 배포 앱 죽는 에러 해결 - 카멜 케이스로 변경
  src/main/java/com/nexus/seoulmate/aws/config/AmazonConfig.java
  src/main/resources/application.yml
Labels: 🐞 bug, 🖧 cicd

#50 [MERGE] 구글 회원 정보 안불러와짐 해결 1
  src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
  src/main/java/com/nexus/seoulmate/config/WebConfig.java
Labels: ⚡ hotfix

#52 [Feat/#30] 친구 검색 및 친구 추천 API 구현
  src/main/java/com/nexus/seoulmate/exception/GlobalExceptionalHandler.java
  src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
  src/main/java/com/nexus/seoulmate/friend/api/FriendController.java
  src/main/java/com/nexus/seoulmate/friend/application/FriendService.java
  src/main/java/com/nexus/seoulmate/friend/application/FriendServiceImpl.java
  src/main/java/com/nexus/seoulmate/friend/converter/FriendConverter.java
  src/main/java/com/nexus/seoulmate/friend/domain/repository/FriendRequestRepository.java
  src/main/java/com/nexus/seoulmate/friend/dto/FriendResponseDTO.java
  src/main/java/com/nexus/seoulmate/member/domain/enums/Languages.java
  src/main/java/com/nexus/seoulmate/member/repository/MemberRepository.java
Labels: ✨ feature

#51 [MOD/#46] 도커에서 레디스 사용하도록 설정
  build.gradle
  docker-compose.yml
  src/main/java/com/nexus/seoulmate/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 🐞 bug

#54 [MERGE] 2025.08.14
  build.gradle
  docker-compose.yml
  src/main/java/com/nexus/seoulmate/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 🖧 cicd

#55 [MERGE] application.yml 수정
  .github/workflows/dev_depoly.yml
Labels: 🐞 bug, 🖧 cicd

#59 [Mod/#46] application 수정, CustomOAuth2User 생성
  .github/workflows/dev_depoly.yml
  build.gradle
  src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
  src/main/java/com/nexus/seoulmate/member/controller/MemberController.java
  src/main/java/com/nexus/seoulmate/member/dto/CustomOAuth2User.java
  src/main/java/com/nexus/seoulmate/member/dto/GoogleResponse.java
  src/main/java/com/nexus/seoulmate/member/service/CustomOAuth2UserService.java
  src/main/resources/application.yml
Labels: 🐞 bug

#68 [MERGE] domain 설정
  src/main/java/com/nexus/seoulmate/common/HealthCheckController.java
  src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
Labels: 🖧 cicd

#71 [Feat/#56] 알림 API 구현
  src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
  src/main/java/com/nexus/seoulmate/exception/status/ErrorStatus.java
  src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
  src/main/java/com/nexus/seoulmate/friend/application/FriendServiceImpl.java
  src/main/java/com/nexus/seoulmate/meeting/domain/Meeting.java
  src/main/java/com/nexus/seoulmate/notification/api/NotificationController.java
  src/main/java/com/nexus/seoulmate/notification/api/dto/NotificationPushDto.java
  src/main/java/com/nexus/seoulmate/notification/api/dto/response/NotificationReadRes.java
  src/main/java/com/nexus/seoulmate/notification/api/dto/response/NotificationRes.java
  src/main/java/com/nexus/seoulmate/notification/application/NotificationPushService.java
  src/main/java/com/nexus/seoulmate/notification/application/NotificationService.java
  src/main/java/com/nexus/seoulmate/notification/domain/LinkTargetType.java
  src/main/java/com/nexus/seoulmate/notification/domain/Notification.java
  src/main/java/com/nexus/seoulmate/notification/domain/repository/NotificationRepository.java
  src/main/java/com/nexus/seoulmate/notification/event/FriendAcceptedEvent.java
  src/main/java/com/nexus/seoulmate/notification/event/FriendRequestedEvent.java
  src/main/java/com/nexus/seoulmate/notification/event/NotificationEventHandler.java
  src/main/java/com/nexus/seoulmate/notification/event/PaymentCaptureEvent.java
  src/main/java/com/nexus/seoulmate/notification/support/NotificationTemplates.java
  src/main/java/com/nexus/seoulmate/order/domain/Order.java
  src/main/java/com/nexus/seoulmate/order/domain/repository/OrderRepository.java
  src/main/java/com/nexus/seoulmate/payment/application/PaymentService.java
Labels: ✨ feature

#74 [Feat/#58] 채팅 api 관련 구현
  build.gradle
  src/main/java/com/nexus/seoulmate/chat/api/ChatController.java
  src/main/java/com/nexus/seoulmate/chat/application/ChatService.java
  src/main/java/com/nexus/seoulmate/chat/application/ChatServiceImpl.java
  src/main/java/com/nexus/seoulmate/chat/converter/ChatConverter.java
  src/main/java/com/nexus/seoulmate/chat/domain/entity/ChatRoom.java
  src/main/java/com/nexus/seoulmate/chat/domain/entity/ChatRoomMember.java
  src/main/java/com/nexus/seoulmate/chat/domain/entity/Message.java
  src/main/java/com/nexus/seoulmate/chat/domain/entity/MsgType.java
  src/main/java/com/nexus/seoulmate/chat/domain/entity/Role.java
  src/main/java/com/nexus/seoulmate/chat/domain/entity/RoomType.java
  src/main/java/com/nexus/seoulmate/chat/domain/repository/ChatRoomMemberRepository.java
  src/main/java/com/nexus/seoulmate/chat/domain/repository/ChatRoomRepository.java
  src/main/java/com/nexus/seoulmate/chat/domain/repository/MessageRepository.java
  src/main/java/com/nexus/seoulmate/chat/dto/ChatRoomDTO.java
  src/main/java/com/nexus/seoulmate/chat/dto/MessageDTO.java
  src/main/java/com/nexus/seoulmate/chat/event/AsyncConfig.java
  src/main/java/com/nexus/seoulmate/chat/event/ChatEvents.java
  src/main/java/com/nexus/seoulmate/chat/event/ChatMessageEventHandler.java
  src/main/java/com/nexus/seoulmate/chat/redis/ChatPublisher.java
  src/main/java/com/nexus/seoulmate/chat/redis/RedisSubscriber.java
  src/main/java/com/nexus/seoulmate/config/RedisConfig.java
  src/main/java/com/nexus/seoulmate/config/WebSocketConfig.java
  src/main/java/com/nexus/seoulmate/exception/status/ErrorStatus.java
  src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
Labels: ✨ feature

#93 [MOD/#46] 레벨테스트 배포 환경에서 안됨 수정, 프론트 리디렉션 주소 수정
  src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
  src/main/java/com/nexus/seoulmate/config/WebConfig.java
  src/main/java/com/nexus/seoulmate/member/handler/CustomAuthenticationSuccessHandler.java
Labels: ⚡ hotfix

#94 [MOD/#46] 프론트 리디렉션 주소 수정
  src/main/java/com/nexus/seoulmate/member/handler/CustomAuthenticationSuccessHandler.java
Labels: 🔨 mod

#95 [MOD/#46] 레벨테스트용 오디오파일 및 프로필사진, 학교 인증서 s3에 업로드
  build.gradle
  src/main/java/com/nexus/seoulmate/aws/s3/S3Folder.java
  src/main/java/com/nexus/seoulmate/aws/service/AmazonS3Service.java
  src/main/java/com/nexus/seoulmate/exception/status/ErrorStatus.java
  src/main/java/com/nexus/seoulmate/member/controller/MemberController.java
  src/main/java/com/nexus/seoulmate/member/domain/GoogleInfo.java
  src/main/java/com/nexus/seoulmate/member/repository/HobbyRepository.java
  src/main/java/com/nexus/seoulmate/member/service/FluentProxyService.java
  src/main/java/com/nexus/seoulmate/member/service/MemberService.java
  src/main/java/com/nexus/seoulmate/member/service/TempStorage.java
  src/main/java/com/nexus/seoulmate/mypage/MyPageService.java
Labels: 🔨 mod

#97 [MOD/#46] cors 에러 해결
  src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
  src/main/java/com/nexus/seoulmate/config/WebConfig.java
Labels: ⚡ hotfix

#98 [MOD/#46] 코스 에러 해결 ...
  src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
  src/main/java/com/nexus/seoulmate/config/WebConfig.java
Labels: ⚡ hotfix

#102 [Bug/#101] 친구 검색 api들 수정
  docker-compose.yml
  src/main/java/com/nexus/seoulmate/friend/api/FriendController.java
  src/main/java/com/nexus/seoulmate/friend/application/FriendService.java
  src/main/java/com/nexus/seoulmate/friend/application/FriendServiceImpl.java
  src/main/java/com/nexus/seoulmate/friend/domain/repository/FriendRequestRepository.java
  src/main/java/com/nexus/seoulmate/friend/dto/FriendResponseDTO.java
  src/main/java/com/nexus/seoulmate/member/repository/MemberRepository.java
Labels: 🐞 bug

#106 [FEAT/#46] 학교 인증서 처리 구현
  build.gradle
  src/main/java/com/nexus/seoulmate/admin/AdminController.java
  src/main/java/com/nexus/seoulmate/admin/AdminService.java
  src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
  src/main/java/com/nexus/seoulmate/config/WebConfig.java
  src/main/java/com/nexus/seoulmate/exception/GlobalExceptionalHandler.java
  src/main/java/com/nexus/seoulmate/exception/status/ErrorStatus.java
  src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
  src/main/java/com/nexus/seoulmate/member/domain/Member.java
  src/main/java/com/nexus/seoulmate/member/repository/MemberRepository.java
  src/main/java/com/nexus/seoulmate/member/service/MemberService.java
  src/main/java/com/nexus/seoulmate/mock/MemberTestDataInitializer.java
  src/main/java/com/nexus/seoulmate/mypage/MyPageController.java
  src/main/java/com/nexus/seoulmate/mypage/MyPageService.java
  src/main/java/com/nexus/seoulmate/mypage/dto/HobbyUpdateRequest.java
Labels: ✨ feature

#111 [Feat/#109] 채팅 안읽은 개수 조회
  src/main/java/com/nexus/seoulmate/chat/api/ChatController.java
  src/main/java/com/nexus/seoulmate/chat/application/ChatService.java
  src/main/java/com/nexus/seoulmate/chat/application/ChatServiceImpl.java
  src/main/java/com/nexus/seoulmate/chat/converter/ChatConverter.java
  src/main/java/com/nexus/seoulmate/chat/domain/entity/ChatRoomMember.java
  src/main/java/com/nexus/seoulmate/chat/domain/repository/ChatRoomMemberRepository.java
  src/main/java/com/nexus/seoulmate/chat/domain/repository/ChatRoomRepository.java
  src/main/java/com/nexus/seoulmate/chat/domain/repository/MessageRepository.java
  src/main/java/com/nexus/seoulmate/chat/dto/ChatRoomDTO.java
  src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
Labels: ✨ feature

#121 [Mod/#116] websocket으로 실시간성 처리
  src/main/java/com/nexus/seoulmate/chat/api/ChatWebSocketController.java
Labels: ✨ feature

#122 [MERGE] 2025.08.21 웹소켓 실시간성 처리
  src/main/java/com/nexus/seoulmate/chat/api/ChatWebSocketController.java
Labels: ✨ feature

#125 [MERGE] 2025.08.21 사용자 상세 조회 반환 값 추가
  src/main/java/com/nexus/seoulmate/friend/application/FriendServiceImpl.java
  src/main/java/com/nexus/seoulmate/friend/converter/FriendConverter.java
  src/main/java/com/nexus/seoulmate/friend/dto/FriendResponseDTO.java
Labels: 🖧 cicd

#132 [MERGE] 2025.08.22 chat용 getcurrentuser 수정
  src/main/java/com/nexus/seoulmate/chat/api/ChatController.java
  src/main/java/com/nexus/seoulmate/chat/api/ChatWebSocketController.java
  src/main/java/com/nexus/seoulmate/chat/application/ChatService.java
  src/main/java/com/nexus/seoulmate/chat/application/ChatServiceImpl.java
Labels: 🐞 bug

#134 [MERGE] 2025.08.22 수정(getCurrentUser 원상복구)
  src/main/java/com/nexus/seoulmate/chat/application/ChatServiceImpl.java
Labels: 🐞 bug

#131 [FIX] 검색 필터 언어별 점수 따로 받기 및 userId getCurrentId 수정
  src/main/java/com/nexus/seoulmate/meeting/api/MeetingPrivateController.java
  src/main/java/com/nexus/seoulmate/meeting/api/dto/request/MeetingSearchReq.java
  src/main/java/com/nexus/seoulmate/meeting/application/privateMeeting/PrivateMeetingService.java
  src/main/java/com/nexus/seoulmate/meeting/application/privateMeeting/PrivateMeetingServiceImpl.java
  src/main/java/com/nexus/seoulmate/meeting/application/search/MeetingSearchServiceImpl.java
  src/main/java/com/nexus/seoulmate/meeting/domain/repository/MeetingCustomRepositoryImpl.java
  src/main/java/com/nexus/seoulmate/member/service/MemberService.java
  src/main/java/com/nexus/seoulmate/notification/api/NotificationController.java
  src/main/java/com/nexus/seoulmate/notification/application/NotificationPushService.java
  src/main/java/com/nexus/seoulmate/notification/application/NotificationService.java
  src/main/java/com/nexus/seoulmate/order/api/OrderController.java
  src/main/java/com/nexus/seoulmate/order/application/OrderService.java
Labels: 🔨 mod

#137 [Feat/#136] 메세지 조회에 userId 필드 추가
  src/main/java/com/nexus/seoulmate/chat/application/ChatServiceImpl.java
  src/main/java/com/nexus/seoulmate/chat/converter/ChatConverter.java
  src/main/java/com/nexus/seoulmate/chat/dto/MessageDTO.java
Labels: ✨ feature

#140 [FEAT] 사설 모임 응답값 수정 및 0원 결제 api 구현
  src/main/java/com/nexus/seoulmate/meeting/api/dto/response/MeetingDetailPrivateRes.java
  src/main/java/com/nexus/seoulmate/meeting/application/privateMeeting/PrivateMeetingServiceImpl.java
  src/main/java/com/nexus/seoulmate/order/application/OrderService.java
  src/main/java/com/nexus/seoulmate/order/domain/Order.java
  src/main/java/com/nexus/seoulmate/payment/application/PaymentService.java
  src/main/java/com/nexus/seoulmate/payment/domain/repository/PaymentRepository.java
Labels: ✨ feature

#154 [MOD] 친구 삭제 api 수정
  Dockerfile
  docker-compose.yml
  src/main/java/com/nexus/seoulmate/chat/application/ChatServiceImpl.java
  src/main/java/com/nexus/seoulmate/chat/converter/ChatConverter.java
  src/main/java/com/nexus/seoulmate/friend/application/FriendServiceImpl.java
  src/main/java/com/nexus/seoulmate/friend/domain/repository/FriendRequestRepository.java
  src/main/java/com/nexus/seoulmate/global/status/ErrorStatus.java
Labels: 🔨 mod
